// device registration
export const DEVICE_REGISTRATION_LOADING = 'DEVICE_REGISTRATION_LOADING';
export const DEVICE_REGISTRATION_SUCCESS = 'DEVICE_REGISTRATION_SUCCESS';
export const DEVICE_REGISTRATION_ERROR = 'DEVICE_REGISTRATION_ERROR';

// user
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

// tasks
export const FETCH_TASKS_LOADING = 'FETCH_TASKS_LOADING';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';

export const ASSIGN_TASKS_LOADING = 'ASSIGN_TASKS_LOADING';
export const ASSIGN_TASKS_SUCCESS = 'ASSIGN_TASKS_SUCCESS';
export const ASSIGN_TASKS_ERROR = 'ASSIGN_TASKS_ERROR';
